# 
# Hello World!
#
#	a simple picoVersat program
#
#   assign regC = {negative, overflow, {(`DATA_W-3){1'b0}}, carry};

# set RB to point to first char
        ldi c0
	wrw RB

# read string from memory and write to char printer 
loop 	rdwb
	rdwb            #need to read twice due to memory 1 cycle delay
	wrw CPRT_BASE
	rdw RB          #load pointer
	addi 1	        #increment by 1
	wrw RB          #store incremented pointer
	rdw R1          #load iterator
	bneqi loop      #go back to loop if non-zero, regA is decremented
	wrw R1          #stores back decremented iterator
        
#finish by writing to invalid address to activate trap
end	wrw 0x7fff
        
# char ascii constants placed here	
c0	.memset '\n'
	.memset 'H'
	.memset 'e'
	.memset 'l'
	.memset 'l'
	.memset 'o'
	.memset ' '
	.memset 'W'
	.memset 'o'
	.memset 'r'
	.memset 'l'
	.memset 'd'
	.memset '!'
	.memset '\n'
	.memset '\r'
	.memset '\n'
