# 
# Multiplier
#
#	a simple picoVersat program

# set R2 iterator 	
	ldi 4
	wrw R2
# set R3 with value 1 (mask)
	ldi 1
	wrw R3
# Fill the registers with 2 numbers
	ldi 0x5  
	wrw R0 
	ldi 0x6 
	wrw R1 
check0
	rdw R1
	and R3 # verifica se 0 ou 1
	beqi dec
	# shiftar e somar se for 1
	ldi 0		
	add R0	
	rdw R0  
	shft -1 # shiftar multiplicand
	wrw R0	
dec	
	rdw R1
	shft 1 # shiftar multiplier
	wrw R1
	rdw R2 # RA = R2	
	sub 1 # RA = RA - R2
	beqi end
	wrw R2 # update R2 (decrement)
	ldi 0 # RA = 0 to jump
	beqi check0
	
#finish by activating trap
end	wrw CPRT_BASE	
	wrw TRAP_BASE
